// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nugunamoney-variants/CleanNavy.tsx": () => import("../components/mockups/nugunamoney-variants/CleanNavy.tsx"),
  "./components/mockups/nugunamoney-variants/DarkLuxury.tsx": () => import("../components/mockups/nugunamoney-variants/DarkLuxury.tsx"),
  "./components/mockups/nugunamoney-variants/WarmModern.tsx": () => import("../components/mockups/nugunamoney-variants/WarmModern.tsx")
};
